# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.28.0/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.28.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/mitsusada/Desktop/code/normal

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/mitsusada/Desktop/code/normal/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.28.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.28.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mitsusada/Desktop/code/normal/build/CMakeFiles /Users/mitsusada/Desktop/code/normal/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mitsusada/Desktop/code/normal/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GUIsample_drag

# Build rule for target.
GUIsample_drag: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GUIsample_drag
.PHONY : GUIsample_drag

# fast build rule for target.
GUIsample_drag/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GUIsample_drag.dir/build.make CMakeFiles/GUIsample_drag.dir/build
.PHONY : GUIsample_drag/fast

GUIsample.o: GUIsample.cpp.o
.PHONY : GUIsample.o

# target to build an object file
GUIsample.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GUIsample_drag.dir/build.make CMakeFiles/GUIsample_drag.dir/GUIsample.cpp.o
.PHONY : GUIsample.cpp.o

GUIsample.i: GUIsample.cpp.i
.PHONY : GUIsample.i

# target to preprocess a source file
GUIsample.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GUIsample_drag.dir/build.make CMakeFiles/GUIsample_drag.dir/GUIsample.cpp.i
.PHONY : GUIsample.cpp.i

GUIsample.s: GUIsample.cpp.s
.PHONY : GUIsample.s

# target to generate assembly for a file
GUIsample.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GUIsample_drag.dir/build.make CMakeFiles/GUIsample_drag.dir/GUIsample.cpp.s
.PHONY : GUIsample.cpp.s

lib/src/ISutils.o: lib/src/ISutils.cpp.o
.PHONY : lib/src/ISutils.o

# target to build an object file
lib/src/ISutils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GUIsample_drag.dir/build.make CMakeFiles/GUIsample_drag.dir/lib/src/ISutils.cpp.o
.PHONY : lib/src/ISutils.cpp.o

lib/src/ISutils.i: lib/src/ISutils.cpp.i
.PHONY : lib/src/ISutils.i

# target to preprocess a source file
lib/src/ISutils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GUIsample_drag.dir/build.make CMakeFiles/GUIsample_drag.dir/lib/src/ISutils.cpp.i
.PHONY : lib/src/ISutils.cpp.i

lib/src/ISutils.s: lib/src/ISutils.cpp.s
.PHONY : lib/src/ISutils.s

# target to generate assembly for a file
lib/src/ISutils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GUIsample_drag.dir/build.make CMakeFiles/GUIsample_drag.dir/lib/src/ISutils.cpp.s
.PHONY : lib/src/ISutils.cpp.s

lib/src/control_panel.o: lib/src/control_panel.cpp.o
.PHONY : lib/src/control_panel.o

# target to build an object file
lib/src/control_panel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GUIsample_drag.dir/build.make CMakeFiles/GUIsample_drag.dir/lib/src/control_panel.cpp.o
.PHONY : lib/src/control_panel.cpp.o

lib/src/control_panel.i: lib/src/control_panel.cpp.i
.PHONY : lib/src/control_panel.i

# target to preprocess a source file
lib/src/control_panel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GUIsample_drag.dir/build.make CMakeFiles/GUIsample_drag.dir/lib/src/control_panel.cpp.i
.PHONY : lib/src/control_panel.cpp.i

lib/src/control_panel.s: lib/src/control_panel.cpp.s
.PHONY : lib/src/control_panel.s

# target to generate assembly for a file
lib/src/control_panel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GUIsample_drag.dir/build.make CMakeFiles/GUIsample_drag.dir/lib/src/control_panel.cpp.s
.PHONY : lib/src/control_panel.cpp.s

lib/src/dnn.o: lib/src/dnn.cpp.o
.PHONY : lib/src/dnn.o

# target to build an object file
lib/src/dnn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GUIsample_drag.dir/build.make CMakeFiles/GUIsample_drag.dir/lib/src/dnn.cpp.o
.PHONY : lib/src/dnn.cpp.o

lib/src/dnn.i: lib/src/dnn.cpp.i
.PHONY : lib/src/dnn.i

# target to preprocess a source file
lib/src/dnn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GUIsample_drag.dir/build.make CMakeFiles/GUIsample_drag.dir/lib/src/dnn.cpp.i
.PHONY : lib/src/dnn.cpp.i

lib/src/dnn.s: lib/src/dnn.cpp.s
.PHONY : lib/src/dnn.s

# target to generate assembly for a file
lib/src/dnn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GUIsample_drag.dir/build.make CMakeFiles/GUIsample_drag.dir/lib/src/dnn.cpp.s
.PHONY : lib/src/dnn.cpp.s

lib/src/load_img.o: lib/src/load_img.cpp.o
.PHONY : lib/src/load_img.o

# target to build an object file
lib/src/load_img.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GUIsample_drag.dir/build.make CMakeFiles/GUIsample_drag.dir/lib/src/load_img.cpp.o
.PHONY : lib/src/load_img.cpp.o

lib/src/load_img.i: lib/src/load_img.cpp.i
.PHONY : lib/src/load_img.i

# target to preprocess a source file
lib/src/load_img.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GUIsample_drag.dir/build.make CMakeFiles/GUIsample_drag.dir/lib/src/load_img.cpp.i
.PHONY : lib/src/load_img.cpp.i

lib/src/load_img.s: lib/src/load_img.cpp.s
.PHONY : lib/src/load_img.s

# target to generate assembly for a file
lib/src/load_img.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GUIsample_drag.dir/build.make CMakeFiles/GUIsample_drag.dir/lib/src/load_img.cpp.s
.PHONY : lib/src/load_img.cpp.s

lib/src/lut.o: lib/src/lut.cpp.o
.PHONY : lib/src/lut.o

# target to build an object file
lib/src/lut.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GUIsample_drag.dir/build.make CMakeFiles/GUIsample_drag.dir/lib/src/lut.cpp.o
.PHONY : lib/src/lut.cpp.o

lib/src/lut.i: lib/src/lut.cpp.i
.PHONY : lib/src/lut.i

# target to preprocess a source file
lib/src/lut.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GUIsample_drag.dir/build.make CMakeFiles/GUIsample_drag.dir/lib/src/lut.cpp.i
.PHONY : lib/src/lut.cpp.i

lib/src/lut.s: lib/src/lut.cpp.s
.PHONY : lib/src/lut.s

# target to generate assembly for a file
lib/src/lut.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GUIsample_drag.dir/build.make CMakeFiles/GUIsample_drag.dir/lib/src/lut.cpp.s
.PHONY : lib/src/lut.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GUIsample_drag"
	@echo "... GUIsample.o"
	@echo "... GUIsample.i"
	@echo "... GUIsample.s"
	@echo "... lib/src/ISutils.o"
	@echo "... lib/src/ISutils.i"
	@echo "... lib/src/ISutils.s"
	@echo "... lib/src/control_panel.o"
	@echo "... lib/src/control_panel.i"
	@echo "... lib/src/control_panel.s"
	@echo "... lib/src/dnn.o"
	@echo "... lib/src/dnn.i"
	@echo "... lib/src/dnn.s"
	@echo "... lib/src/load_img.o"
	@echo "... lib/src/load_img.i"
	@echo "... lib/src/load_img.s"
	@echo "... lib/src/lut.o"
	@echo "... lib/src/lut.i"
	@echo "... lib/src/lut.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

